name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal --logger trx --results-directory "TestResults"
    - name: Upload dotnet test results
      uses: actions/upload-artifact@v3
      with:
        name: dotnet-results
        path: TestResults
      # Use always() to always run this step to publish test results when there are test failures
      if: ${{ always() }}
      
  code-quality:
    runs-on: ubuntu-latest
    name: Code Climate Standalone
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Run Code Climate
        uses: erzz/codeclimate-standalone@v0.0.4
        with:
          html_report: true
      - name: Upload Report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: Code Climate Report
          path: codeclimate-report.html
